export const path = {
  HOME: "/*",
  LOGIN: "login",
  NOTFOUND: "not-found",
  LISTCOURSE: "list-course",
  LISTMYCOURSE: "list-my-course",
  LISTCOURSEOFTEACHER: "list-course-of-teacher",
  LISTDEPARTMENT: "department",
  COURSE: "course",
  CLASSPAGE: "course/class",
  ADDCOURSE: "course/add",
  MANAGECOURSE: "manage-course",
  ENROLMETHOD: "course/enrol-method",
  USERENROLED: "course/user-enroled",
  ENROLMENTPAGE: "course/enrolment-page",
  PRACTICEPAGE: "practice-page",
  CREATEPRACTICE: "practice/create",
  UPDATEPRACTICE: "practice/update",
  FOLDER: "folder/document",
  EXAM: 'exam'
};
