export const path = {
  HOME: "/*",
  LOGIN: "login",
  NOTFOUND: "not-found",
  LISTCOURSE: "list-course",
  LISTDEPARTMENT: "department",
  COURSE: "course",
  CLASSPAGE: "course/class",
  ADDCOURSE: "course/add",
  MANAGECOURSE: "manage-course",
  ENROLMETHOD: "course/enrol-method",
  USERENROLED: "course/user-enroled",
  PRACTICEPAGE: "practice-page",
  CREATEPRACTICE: "practice/create",
  FOLDER: "folder/document",
};
